Update tap (~0.4.0) so that tests run again
On a fresh clone, using node v0.10.28, you end would end up with a weird
error:

/tmp/node-ini/node_modules/tap/node_modules/tap-runner/runner.js:15
  Runner.super.call(this, diag)
               ^
TypeError: Cannot call method 'call' of undefined